# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Variables
        id: variables
        uses: actions/github-script@v3
        with:
          script: |
            const version = context.ref.split("/").pop();
            const tagName = version.slice(1, version.length);
            core.setOutput('versionTag' , tagName);
      - id: set-matrix
        run: |
          JSON=$(cat ./your.json)
          echo "::set-output name=matrix::${JSON//'%'/'%25'}"
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.variables.outputs.versionTag }}
        run: |
          echo "JSON is: ${{steps.set-matrix-outputs.matrix}}" 
          echo $RELEASE_VERSION
          echo "Version is: ${{ steps.variables.outputs.versionTag }} "
     
